# Generated by Django 3.2.4 on 2021-06-16 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_carrera', models.CharField(max_length=50)),
                ('duracion', models.PositiveSmallIntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=30)),
                ('creditos_curso', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('carnet_docente', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('apellidoP_docente', models.CharField(max_length=30)),
                ('apellidoM_docente', models.CharField(max_length=30)),
                ('nombre_docente', models.CharField(max_length=30)),
                ('correo_docente', models.EmailField(max_length=100)),
                ('usuario_docente', models.CharField(max_length=50)),
                ('contra_docente', models.CharField(max_length=50)),
                ('sexo_docente', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('carnet_est', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('apellidoP_est', models.CharField(max_length=30)),
                ('apellidoM_est', models.CharField(max_length=30)),
                ('nombre_est', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('correo_est', models.EmailField(max_length=100)),
                ('usuario_est', models.CharField(max_length=50)),
                ('contra_est', models.CharField(max_length=50)),
                ('sexo_est', models.CharField(max_length=1)),
                ('vigencia', models.BooleanField(default=True)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ita.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('carnet_personal', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('apellidoP_personal', models.CharField(max_length=30)),
                ('apellidoM_personal', models.CharField(max_length=30)),
                ('nombre_personal', models.CharField(max_length=30)),
                ('correo_personal', models.EmailField(max_length=100)),
                ('usuario_personal', models.CharField(max_length=50)),
                ('contra_personal', models.CharField(max_length=50)),
                ('tipo_personal', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id_matricula', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_matriculacion', models.DateTimeField(auto_now_add=True)),
                ('carnet_est', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ita.estudiante')),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ita.carrera')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ita.curso')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='carnet_docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ita.docente'),
        ),
    ]
