# Generated by Django 3.2.4 on 2021-06-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
