# Generated by Django 3.2.4 on 2021-06-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ita', '0002_personal_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='creditos_curso',
        ),
        migrations.AddField(
            model_name='curso',
            name='cantidad_estudiantes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
