# Generated by Django 3.2.4 on 2021-06-22 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ita', '0003_auto_20210622_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='id_carrera',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ita.carrera'),
            preserve_default=False,
        ),
    ]
