# Generated by Django 3.2.4 on 2021-06-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ita', '0004_curso_id_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='gestion',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='curso',
            name='turno_curso',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
