# Generated by Django 3.2.4 on 2021-06-22 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ita', '0005_auto_20210622_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='turno_curso',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='id_carrera',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ita.carrera'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nuevo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='turno',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
