# Generated by Django 3.2.4 on 2021-06-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ita', '0006_auto_20210622_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nombre_curso',
            field=models.CharField(max_length=50),
        ),
    ]
