# Generated by Django 3.2.4 on 2021-06-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ita', '0007_alter_curso_nombre_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='horas',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='curso',
            name='pre_requisito',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
