# Generated by Django 3.2.4 on 2021-06-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ita', '0008_auto_20210623_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='pre_requisito',
            field=models.CharField(max_length=30),
        ),
    ]
