# Generated by Django 3.2.4 on 2021-06-27 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ita', '0009_alter_curso_pre_requisito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='id_curso',
        ),
        migrations.CreateModel(
            name='CursosEstudiante',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('aprobado', models.BooleanField(default=False)),
                ('carnet_est', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ita.estudiante')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ita.curso')),
            ],
        ),
    ]
