# Generated by Django 3.2.4 on 2021-06-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ita', '0010_auto_20210627_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosestudiante',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
