# Generated by Django 3.2.4 on 2021-06-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ita', '0011_alter_cursosestudiante_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
